name: astx
channels:
  - nodefaults
  - conda-forge
dependencies:
  - graphviz
  - python
  - poetry >=1.5
  - nodejs # used by semantic-release
  - shellcheck
  - pip
  - pip:
      # distlib issue
      - distlib==1.1.0
      - paginate==0.56
