name: astx
channels:
  - nodefaults
  - conda-forge
dependencies:
  - graphviz
  - python
  - poetry >=1.5
  - nodejs # used by semantic-release
  - shellcheck
  - pip
  - pip:
      # distlib issue
      - paginate
      # 'PosixPath' object has no attribute 'endswith'
      - mkdocs-exclude >=1.0.2
