name: astx
channels:
  - nodefaults
  - conda-forge
dependencies:
  - graphviz
  - python >=3.8.1,<4
  - poetry >=1.5
  - nodejs # used by semantic-release
  - shellcheck
  - pip
  - pip:
      - paginate
