name: astx
channels:
  - nodefaults
  - conda-forge
dependencies:
  - graphviz
  - openjdk # java is required by asciinet
  - python
  - poetry >=1.5
  - nodejs # used by semantic-release
  - shellcheck
  - pip
  - pip:
      # distlib issue
      - paginate
